# 4x4 array

In [2]:
import numpy as np


In [3]:
array = np.arange(2, 33, 2).reshape(4, 4)

In [4]:
mean = np.mean(array)

In [7]:
std_dev = np.std(array)

In [8]:
condition = np.abs(array - mean) < 0.5 * std_dev

In [9]:
result = array[condition]


In [10]:
print("Original Array:")

Original Array:


In [11]:
print(array)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [12]:
print("\nValues within 1/2 standard deviations of the mean:")



Values within 1/2 standard deviations of the mean:


In [13]:
print(result)


[14 16 18 20]


In [14]:
print (result)

[14 16 18 20]
