# nxn Array

In [1]:
import numpy as np


In [2]:
n = int(input("Enter the value of n: "))


Enter the value of n:  4


In [3]:
col_indices = np.arange(1, n + 1).reshape(-1, 1)


In [4]:
result = col_indices + np.zeros((n, n), dtype=int)


In [5]:
print(result)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
